"""Add new features

Revision ID: 009723a6f80a
Revises: e88d328255a0
Create Date: 2026-09-16 22:09:10.405107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009723a6f80a'
down_revision: Union[str, Sequence[str], None] = 'e88d328255a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.add_column('expenses', sa.Column('category', sa.String(), nullable=True))
    op.add_column('members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Generate VAPID keys and insert them into system_config
    import base64
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives import serialization
    
    # Check if they exist first, though in this upgrade step the table is new
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT value FROM system_config WHERE key='vapid_private'")).fetchone()
    if not res:
        private_key = ec.generate_private_key(ec.SECP256R1())
        priv_bytes = private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()
        )
        pub_bytes = private_key.public_key().public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.UncompressedPoint
        )
        pub_b64 = base64.urlsafe_b64encode(pub_bytes).decode('utf-8').rstrip('=')
        
        conn.execute(sa.text("INSERT INTO system_config (key, value) VALUES ('vapid_private', :val)"), {"val": priv_bytes.decode('utf-8')})
        conn.execute(sa.text("INSERT INTO system_config (key, value) VALUES ('vapid_public', :val)"), {"val": pub_b64})



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_admin')
    op.drop_column('expenses', 'category')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('system_config')
    # ### end Alembic commands ###
