"""Add balance to Member

Revision ID: dbf9f5f93a7e
Revises: 009723a6f80a
Create Date: 2026-09-16 22:53:57.119677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf9f5f93a7e'
down_revision: Union[str, Sequence[str], None] = '009723a6f80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_context().bind
    from sqlalchemy import inspect
    inspector = inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('members')]
    if 'balance' in columns:
        print("Column balance already exists. Skipping.")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('balance', sa.Numeric(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'balance')
    # ### end Alembic commands ###
